os: osx
language: swift
osx_image: xcode10.1
xcode_project: UB.xcodeproj
xcode_scheme: UB.Package

jobs:
  fast_finish: true
  include:
    - script: make test
    - script:
        - make xcode
        - make lint
  allow_failures:
    - script: make lint

notifications:
  email: false
