os: osx
language: swift
osx_image: xcode10.3
xcode_project: UB.xcodeproj
xcode_scheme: UB.Package

branches:
  only:
    - master

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.html)|^(LICENSE)|^(docs)'
      then
        echo "Only docs were updated, not running the full CI."
        exit
      fi

install: make xcode

jobs:
  include:
    - stage: Test
      name: Run Tests
      script: make test

   - stage: Build Docs
     name: Build docs
     script: make docs
     if:
         tag IS present
     
deploy: 
    provider: pages
    skip_cleanup: true
    github_token: $GH_PAGES
    keep_history: true
    local_dir: ./docs
    on:
        tag: true

notifications:
  email: false
